### PR TITLE
Eliminate views in SQL queries, exclude CTGovProtocol and related doc-types from publishing. Updated on PROD 2017-09-29, VE.

### PR DESCRIPTION
**Pull request by venglisch**
My first pull request.

### CODE REVIEW

**Comment by bkline** [comment]
Cool! :+1: So the enhancement of eliminating the slow view has made it all the way to production?

**Comment by venglisch** [comment]
Yes, one of the views in the SQL queries has been eliminated with this update.

**Comment by bkline** [comment]
Pull request approved and merged. I'll let you drop the branch (and if you're feeling adventurous, bring fermi up to date with the changes).

**Comment by venglisch** [comment]
Do I delete the branch here in github and then update my local repo, do I remove my local branch and then push the changes, or does it even matter which way it's approached?

**Comment by bkline** [comment]
I generally do it the first way (GitHub first, then pull the changes down), but it should work either way.

**Pull request merged**
